# Builds EarthNow: the application executable and the bespoke setup program (DEL-001).
# Ported from ED Voyage Companion's build.ps1.
#
#   ./build.ps1                 build the application and the setup program
#   ./build.ps1 -SkipInstaller  build only the application
#
# Outputs:
#   build/bin/EarthNow.exe                   the application
#   dist-installer/EarthNowSetup.exe         the setup program, carrying the
#                                            application as an embedded payload
#
# The version is read from VERSION and passed into both programs with -ldflags, so
# no version literal lives anywhere in the source. Note that -X only reaches a var;
# against a const it silently does nothing, which is why appVersion is a var.
param(
    [switch]$SkipInstaller
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$version = (Get-Content (Join-Path $root 'VERSION')).Trim()
$ldflags = "-X main.appVersion=$version"
Write-Host "Building EarthNow $version"

# Cgo is pinned off rather than left to whatever the machine happens to default to.
# Nothing here wants a C toolchain, so there is nothing to lose by disabling it. Off
# is already the default on a machine with no C compiler, which is precisely why
# leaving it implicit is a trap: the first machine with one would quietly start
# producing a different binary and nothing would say so. It is set before the gate as
# well as the build, so the tests exercise the configuration that ships.
$env:CGO_ENABLED = '0'

# Verify before building, with no way past it. A gate that can be skipped is a gate
# that is skipped on the day it would have caught something, so there is no switch to
# turn this off: run test.ps1 directly while working; let the build insist.
& (Join-Path $root 'test.ps1')
if ($LASTEXITCODE -ne 0) { throw "test.ps1 failed with exit code $LASTEXITCODE" }

# One icon is the whole identity (DEL-004): the application executable, the setup
# executable, the Start Menu and Desktop shortcuts and the taskbar button all end up
# wearing it. The shortcuts and the taskbar each read it out of the binary rather
# than carrying a copy, so placing it on the two executables is the whole job.
#
# The .ico is generated by tools/genicons.py and committed, rather than left for
# Wails to derive from appicon.png at build time. Wails only derives one when the
# file is absent, so relying on that would mean deleting and hoping; copying a known
# file leaves nothing to hope about.
# The setup window's own header mark is not handled here: tools/genicons.py writes
# it straight into the setup page's directory, small enough to load as it is. That
# copy is committed alongside the page.
$master = Join-Path $root 'assets/application-icon.png'
$masterIco = Join-Path $root 'assets/application-icon.ico'
if (-not ((Test-Path $master) -and (Test-Path $masterIco))) {
    throw 'Missing assets/application-icon.png or .ico: run tools/genicons.py first.'
}
Write-Host 'Applying the application icon...'
foreach ($dir in @('build', 'installer/build')) {
    New-Item -ItemType Directory -Force -Path (Join-Path $root "$dir/windows") | Out-Null
    Copy-Item $master (Join-Path $root "$dir/appicon.png") -Force
    Copy-Item $masterIco (Join-Path $root "$dir/windows/icon.ico") -Force
}

Write-Host 'Building the application...'
wails build -ldflags $ldflags
if ($LASTEXITCODE -ne 0) { throw "wails build failed with exit code $LASTEXITCODE" }

if ($SkipInstaller) {
    Write-Host 'Done: build/bin/EarthNow.exe'
    exit 0
}

Write-Host 'Packaging the application as the setup payload...'
$payload = Join-Path $root 'installer/payload.zip'
if (Test-Path $payload) { Remove-Item $payload -Force }
Compress-Archive -Path (Join-Path $root 'build/bin/*') -DestinationPath $payload

# The licence has one home, LICENSE at the repository root. The setup page has no
# build step to read it from there, so it is copied in beside the page for the
# embed to carry; the copy is ignored by git so the two can never be committed apart.
Write-Host 'Placing the licence beside the setup page...'
Copy-Item (Join-Path $root 'LICENSE') (Join-Path $root 'installer/frontend/dist/LICENSE.txt') -Force

Write-Host 'Building the setup program...'
Push-Location (Join-Path $root 'installer')
try {
    wails build -ldflags $ldflags
    if ($LASTEXITCODE -ne 0) { throw "wails build failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

Write-Host 'Collecting the setup program...'
$distDir = Join-Path $root 'dist-installer'
New-Item -ItemType Directory -Force -Path $distDir | Out-Null
$built = Join-Path $root 'installer/build/bin/EarthNowSetup.exe'
Copy-Item $built (Join-Path $distDir 'EarthNowSetup.exe') -Force

# Put the empty-zip placeholder back, so `go build ./...` and the tests keep working
# without a full build and so a multi-megabyte payload never reaches a commit.
$empty = [byte[]](0x50, 0x4B, 0x05, 0x06) + (New-Object byte[] 18)
[System.IO.File]::WriteAllBytes($payload, $empty)

Write-Host "Done: dist-installer/EarthNowSetup.exe ($version)"
