// Package geo resolves a point to its nearest populated place and the country
// it lies in, offline, from embedded Natural Earth data (REQUIREMENTS.md
// FR-GEO-001 to 005, FR-GEO-008). Measured in the Phase 0 spike: about 0.5 ms
// per lookup over 7,342 places and 258 countries.
package geo

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"strings"
)

// The data is generated by tools/geodata.py from Natural Earth 1:10m populated
// places (simple) and admin 0 countries; public domain.
var (
	//go:embed data/places.json.gz
	placesGz []byte
	//go:embed data/countries.json.gz
	countriesGz []byte
)

// earthRadiusKm is the IUGG mean Earth radius.
const earthRadiusKm = 6371.0088

// compassPoints are the eight directions a bearing is rounded to (FR-GEO-005).
var compassPoints = [...]string{"N", "NE", "E", "SE", "S", "SW", "W", "NW"}

// corrections repair source errors found by measurement, each keyed by the
// wrong text. Natural Earth spells French Guiana's region "Guinaa" (raw bytes
// checked 2026-09-23).
var corrections = map[string]string{"Guinaa": "Guyane"}

type place struct {
	Name    string  `json:"n"`
	Region  string  `json:"r"`
	Country string  `json:"c"`
	Lat     float64 `json:"lat"`
	Lng     float64 `json:"lng"`
}

type country struct {
	Name  string         `json:"n"`
	Rings [][][2]float64 `json:"r"`
	box   [4]float64     // minLng, minLat, maxLng, maxLat
}

// Gazetteer answers place lines from the embedded data.
type Gazetteer struct {
	places    []place
	countries []country
}

// Load decodes the embedded data.
func Load() (*Gazetteer, error) {
	return load(placesGz, countriesGz)
}

func load(placesData, countriesData []byte) (*Gazetteer, error) {
	g := &Gazetteer{}
	if err := gunzipJSON(placesData, &g.places); err != nil {
		return nil, fmt.Errorf("places: %w", err)
	}
	if err := gunzipJSON(countriesData, &g.countries); err != nil {
		return nil, fmt.Errorf("countries: %w", err)
	}
	if len(g.places) == 0 {
		return nil, fmt.Errorf("places: none in the data")
	}
	for i := range g.places {
		p := &g.places[i]
		p.Name, p.Region, p.Country = correct(p.Name), correct(p.Region), correct(p.Country)
	}
	for i := range g.countries {
		g.countries[i].Name = correct(g.countries[i].Name)
		g.countries[i].box = bounds(g.countries[i].Rings)
	}
	return g, nil
}

func correct(s string) string {
	if fixed, ok := corrections[s]; ok {
		return fixed
	}
	return s
}

func gunzipJSON(gz []byte, into any) error {
	r, err := gzip.NewReader(bytes.NewReader(gz))
	if err != nil {
		return err
	}
	raw, err := io.ReadAll(r)
	if err != nil {
		return err
	}
	return json.Unmarshal(raw, into)
}

func bounds(rings [][][2]float64) [4]float64 {
	b := [4]float64{math.Inf(1), math.Inf(1), math.Inf(-1), math.Inf(-1)}
	for _, ring := range rings {
		for _, p := range ring {
			b[0], b[1] = math.Min(b[0], p[0]), math.Min(b[1], p[1])
			b[2], b[3] = math.Max(b[2], p[0]), math.Max(b[3], p[1])
		}
	}
	return b
}

func radians(d float64) float64 { return d * math.Pi / 180 }

// haversineKm is the great-circle distance between two points.
func haversineKm(lat1, lng1, lat2, lng2 float64) float64 {
	dLat, dLng := radians(lat2-lat1), radians(lng2-lng1)
	a := math.Sin(dLat/2)*math.Sin(dLat/2) +
		math.Cos(radians(lat1))*math.Cos(radians(lat2))*math.Sin(dLng/2)*math.Sin(dLng/2)
	return 2 * earthRadiusKm * math.Asin(math.Sqrt(a))
}

// compass is the initial bearing from the first point to the second, rounded
// to one of eight points.
func compass(lat1, lng1, lat2, lng2 float64) string {
	y := math.Sin(radians(lng2-lng1)) * math.Cos(radians(lat2))
	x := math.Cos(radians(lat1))*math.Sin(radians(lat2)) -
		math.Sin(radians(lat1))*math.Cos(radians(lat2))*math.Cos(radians(lng2-lng1))
	deg := math.Mod(math.Atan2(y, x)*180/math.Pi+360, 360)
	step := 360.0 / float64(len(compassPoints))
	return compassPoints[int(math.Round(deg/step))%len(compassPoints)]
}

// inRing is the even-odd ray test; a country's rings together give holes.
func inRing(ring [][2]float64, lng, lat float64) bool {
	inside := false
	for i, j := 0, len(ring)-1; i < len(ring); j, i = i, i+1 {
		xi, yi, xj, yj := ring[i][0], ring[i][1], ring[j][0], ring[j][1]
		if (yi > lat) != (yj > lat) && lng < (xj-xi)*(lat-yi)/(yj-yi)+xi {
			inside = !inside
		}
	}
	return inside
}

func (g *Gazetteer) countryAt(lat, lng float64) string {
	for _, c := range g.countries {
		if lng < c.box[0] || lng > c.box[2] || lat < c.box[1] || lat > c.box[3] {
			continue
		}
		inside := false
		for _, ring := range c.Rings {
			if inRing(ring, lng, lat) {
				inside = !inside
			}
		}
		if inside {
			return c.Name
		}
	}
	return ""
}

// Describe builds the place line: "23 km NE of Tromsø, Troms, Norway", "In
// Germany; 5 km E of Strasbourg, Alsace, France" or "At sea; ...".
func (g *Gazetteer) Describe(lat, lng float64) string {
	best, bestKm := 0, math.Inf(1)
	for i, p := range g.places {
		if d := haversineKm(p.Lat, p.Lng, lat, lng); d < bestKm {
			best, bestKm = i, d
		}
	}
	p := g.places[best]
	// Place names repeat across regions (two Montanas: Bulgaria, Alaska), so
	// the region is named unless blank or the place's own name.
	where := p.Name
	if p.Region != "" && p.Region != p.Name {
		where += ", " + p.Region
	}
	where += ", " + p.Country
	km := int(math.Round(bestKm))
	relative := fmt.Sprintf("%s km %s of %s", thousands(km), compass(p.Lat, p.Lng, lat, lng), where)
	if km == 0 {
		relative = "At " + where
	}
	switch in := g.countryAt(lat, lng); {
	case in == "":
		return "At sea; " + lowerFirst(relative)
	case in == p.Country:
		return relative
	default:
		return fmt.Sprintf("In %s; %s", in, lowerFirst(relative))
	}
}

// lowerFirst turns a leading "At " into "at " once the line gains a prefix.
func lowerFirst(s string) string {
	if rest, ok := strings.CutPrefix(s, "At "); ok {
		return "at " + rest
	}
	return s
}

func thousands(n int) string {
	s := fmt.Sprint(n)
	for i := len(s) - 3; i > 0; i -= 3 {
		s = s[:i] + "," + s[i:]
	}
	return s
}
